// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ConvertRequest struct {
	LongURL string `json:"longURL" validate:"required"`
}

type ConvertResponse struct {
	ShortURL string `json:"shortURL"`
}

type ShowRequest struct {
	ShortURL string `path:"shortURL" validate:"required"`
}

type ShowResponse struct {
	LongURL string `json:"longURL"`
}
